import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/provider/session_provider";
import { auth } from "@/lib/auth";


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400"], variable: "--font-Poppins" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = auth()
  return (
    <html lang="en">
      <body className={cn(inter.className, poppins.variable)}>
        <AuthProvider session={session}>
            {children}
            <Toaster position="top-center" richColors/>
        </AuthProvider>
      </body>
    </html>
  );
}
